### ISSUE TITLE
Update the UG

### ISSUE THREAD

**Issue by squeakysquak** [AY2122S1-CS2103T-T09-4/tp#15]
Move the draft UG content into the User Guide page in your repository. Update the content as necessary. If a feature is not implemented in the current version, you can either omit it from the UG or mark it as 'Coming soon' (e.g., ## Archiving contacts [coming soon]).

As mentioned before, while it is more convenient for one person to update the entire UG, we recommend that each person updates their own part of the docs so that we can easily track the contribution of each member using RepoSense.

**Comment by Cyn7hius** [comment]
Updated the UG to include the skeleton version of FAST v1.2

Some details have not been updated yet, and will be done by the respective dev 
before v1.2
