### ISSUE TITLE
Update the DG: user stories, glossary, NFRs, use cases

### ISSUE THREAD

**Issue by trash-bin99** [AY2122S1-CS2103T-T09-4/tp#16]
Add the following to the DG, based on your project notes from the previous weeks.

Some examples of these can be found in the AB3 Developer Guide.
        
Target user profile, value proposition, and user stories: Update the target user profile and value proposition to match the project direction you have selected. Give a list of the user stories (and update/delete existing ones, if applicable), including priorities. This can include user stories considered but will not be included in the final product.

Use cases: Give use cases (textual form) for a few representative user stories that need multiple steps to complete. e.g. Adding a tag to a person (assume the user needs to find the person first)
        
Non-functional requirements: Note: Many of the given project constraints can be considered NFRs. You can add more. e.g. performance requirements, usability requirements, scalability requirements, etc.
        
Glossary: Define terms that are worth recording.

**Comment by trash-bin99** [comment]
User Stories: Wang Bin
NFR and Glossary: Teng Hon
Use Cases: Pei Yuan
Target user profile, value proposition: Calvin

**Comment by Th-429B** [comment]
Done NFR and Glossary

**Comment by Py0000** [comment]
Done Use Cases
