### ISSUE TITLE
[PE-D] Unable to delete after adding 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T09-4/tp#186]
![image.png](https://raw.githubusercontent.com/Pulpy-y/ped/main/files/a722612e-cac5-448c-ab52-c4bd40b9042a.png)

Somehow couldn't delete the last three which I just added.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Pulpy-y/ped#9

**Comment by Py0000** [comment]
See #179
