### ISSUE TITLE
[PE-D] Undo Appointments should return the previous appointment

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T09-4/tp#194]
https://ay2122s1-cs2103t-t09-4.github.io/tp/UserGuide.html#undo-marking-of-completed-appointment-ua

> This also allows you to undo your mistake if you have accidentally marked an appointment as completed.

If its a mistake that I accidentally marked my appointment as done, if I undo the appointment, then I should expect to see the last appointment date. The current implementation makes it looks like I have no more appointments with the client. 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: lizchow/ped#9

**Comment by Py0000** [comment]
Suggested Fix: Edit the description in UG
