### ISSUE TITLE
Update DG

### ISSUE THREAD

**Issue by Py0000** [AY2122S1-CS2103T-T09-4/tp#205]
1) Update `Design` Section 
2) Each of one of us to update our own feature under `Implementation` feature
3) Update `Manual Testing` Section. 

**Update Status**
- [x] Teng hon
- [x] Calvin
- [x] Ethan
- [x] Wang bin
- [X] Peiyuan

**Comment by Th-429B** [comment]
Everyone has completed their share of updating DG.
