### ISSUE TITLE
DG final fixes

### ISSUE THREAD

**Issue by Th-429B** [AY2122S1-CS2103T-T09-4/tp#251]
![image](https://user-images.githubusercontent.com/64453504/140704837-a8e36ff4-6e57-409d-b5cc-19460012df49.png)

did not include TagComponent and PersonComponent, missing blank line

**Comment by Py0000** [comment]
![image](https://user-images.githubusercontent.com/77230044/140705155-eef46cad-206a-4b85-bb97-63e2f9ce8fa8.png)

**Comment by Py0000** [comment]
New line
![image](https://user-images.githubusercontent.com/77230044/140705304-aa95793f-5a8e-415f-a262-a6541c714904.png)
![image](https://user-images.githubusercontent.com/77230044/140705372-3787ee80-9876-41c7-b129-7291fb0307b5.png)
![image](https://user-images.githubusercontent.com/77230044/140705398-450cc621-5023-4e9d-b6b2-34f154b51c49.png)
![image](https://user-images.githubusercontent.com/77230044/140705434-f8b35c50-c3ec-4c62-84fa-959f22b03f20.png)
