### ISSUE TITLE
Update AboutUs page 

### ISSUE THREAD

**Issue by Th-429B** [AY2122S1-CS2103T-T09-4/tp#9]
Each member adds their own details including a profile picture to ```/docs/AboutUs.md```.
File name of the photo should be in all **lowercase**.
eg. ```docs/images/githbub_username_in_lower_case.png```

**Comment by Py0000** [comment]
Updated my portion of AboutUs page.

**Comment by Th-429B** [comment]
Every member has updated their AboutUs page. Closing the issue.
